/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dto.PersonaFisicaDTO;
import entidades.TipoDocumento;
import gestores.GestorDePersonas;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nahuel Riquelme
 */
public class PanelGestionarPasajeros extends javax.swing.JPanel {
    private final VentanaPrincipal frame;
    private final GestorDePersonas gestorPersonas = GestorDePersonas.getInstance();
    private PasajerosTableModel model;
    private int row_selected;
    private List<PersonaFisicaDTO> pasajerosDTO;
    private List<PersonaFisicaDTO> paginado;
    public static int MAX_FILAS = 10;
    private int pisoInclusivo = 0;
    private int techoExclusivo =  MAX_FILAS;
    private int pagActual;
    private int pagsTotales;

    /**
     * Creates new form PanelGestionarPasajeros
     * @param frame
     */
    public PanelGestionarPasajeros(VentanaPrincipal frame) {
        initComponents();
        this.frame = frame;
        cargarModelo();
        
//        jTable1.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
//            int filasSeleccionadas = jTable1.getSelectedRowCount();
//            if(filasSeleccionadas == 1){
//                int row_selected = jTable1.getSelectedRow();
//                System.out.println(jTable1.getValueAt(row_selected,1));
//            }
//        });
//limitando cantidad caracteres
        JTextApellido.setDocument(new JTextFieldLimit(32));
        JTextNombre.setDocument(new JTextFieldLimit(32));
        JTextDocumento.setDocument(new JTextFieldLimit(16));
    }
    
    private void cargarModelo(){
        model = new PasajerosTableModel();
        jTable1.setModel(model);  
    
    //Le agrego el radiobutton a la tabla
    class MyTableCellRenderer extends JRadioButton implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
           this.setSelected(isSelected);
            setBackground(Color.WHITE);
           return this;
        }
    }
        TableColumnModel cm = jTable1.getColumnModel();
        cm.addColumn(new TableColumn(0, 10, new MyTableCellRenderer(), null));
        cm.moveColumn(cm.getColumnCount() - 1, 0);
        // Instanciamos el TableRowSorter y lo añadimos al JTable para ordernar por columna
        TableRowSorter<TableModel> ordenarTabla = new TableRowSorter<>(model);
        jTable1.setRowSorter(ordenarTabla);
    }

    private void cargarDatosBusqueda(){
        String nombre = JTextNombre.getText();
        String apellido = JTextApellido.getText();
        String tipoDocumento;
        if(jComboBoxTipoDoc.getSelectedItem() == null){
            tipoDocumento = "";
        }else tipoDocumento = jComboBoxTipoDoc.getSelectedItem().toString();
        String nroDocumento = JTextDocumento.getText();
        pasajerosDTO = gestorPersonas.buscarPasajero(nombre,apellido,tipoDocumento,nroDocumento);
        paginarDatos();
    }
    
    private void paginarDatos(){
        //Modifico el jLabel con la cantidad de paginas
        pagActual = pisoInclusivo / MAX_FILAS + 1;
        pagsTotales = pasajerosDTO.size() / MAX_FILAS + ((pasajerosDTO.size() % MAX_FILAS == 0)? 0 : 1);
        lPag.setText("Página "+pagActual+"/"+pagsTotales);
        
        //Carga la pagina actual
        cargarPagina();
        
        if (pasajerosDTO.size() / MAX_FILAS > 0)
            bAdelante.setEnabled(true);
        else
            bAdelante.setEnabled(false);
    }
    
    private void cargarPagina(){
        paginado = pasajerosDTO.stream().skip((pagActual-1)*MAX_FILAS).limit(MAX_FILAS).collect(Collectors.toList());
        model.setDatos(paginado);
        model.fireTableDataChanged(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTextNombre = new javax.swing.JTextField();
        jComboBoxTipoDoc = new javax.swing.JComboBox<>();
        DefaultComboBoxModel tipoDocModel = new DefaultComboBoxModel();
        tipoDocModel.addElement(null);
        for(TipoDocumento t: TipoDocumento.values()){
            tipoDocModel.addElement(t);
        }
        jComboBoxTipoDoc.setModel(tipoDocModel);
        jComboBoxTipoDoc.setSelectedItem(TipoDocumento.DNI);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTextApellido = new javax.swing.JTextField();
        JTextDocumento = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSiguiente = new javax.swing.JButton();
        bAdelante = new javax.swing.JButton();
        lPag = new javax.swing.JLabel();
        bAtras = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setText("Nombres(s)");

        jLabel2.setText("Tipo de documento");

        JTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTextNombreKeyReleased(evt);
            }
        });

        jComboBoxTipoDoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoDocItemStateChanged(evt);
            }
        });

        jLabel4.setText("Apellido(s)");

        jLabel5.setText("Número de documento");

        JTextApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTextApellidoKeyReleased(evt);
            }
        });

        JTextDocumento.setEnabled(false);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextDocumento)
                    .addComponent(JTextApellido))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JTextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JTextApellido, JTextDocumento, JTextNombre, jComboBoxTipoDoc});

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Criterios de búsqueda");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        bAdelante.setText(">");
        bAdelante.setEnabled(false);
        bAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdelanteActionPerformed(evt);
            }
        });

        lPag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lPag.setText("Página 0/0");

        bAtras.setText("<");
        bAtras.setDoubleBuffered(true);
        bAtras.setEnabled(false);
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAdelante)
                        .addGap(252, 252, 252)
                        .addComponent(jButtonSiguiente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPag)
                    .addComponent(bAdelante)
                    .addComponent(bAtras)
                    .addComponent(jButtonSiguiente))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Resultados de búsqueda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        //Carga los datos en la tabla
        cargarDatosBusqueda();
        if (pasajerosDTO.isEmpty()){
            Object[] options = { "No", "Si"};
            int opcion = JOptionPane.showOptionDialog(null, "¿Desea dar de alta un pasajero?", "Pasajero no encontrado",
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcion == 1) {
                System.out.println("Pasar a la interface alta de pasajero");
                frame.cambiarPanel(VentanaPrincipal.PANE_DAR_ALTA_PASAJERO);
            } else System.out.println("Seguir buscando");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //Guardo los datos de la fila seleccionada
        int filasSeleccionadas = jTable1.getSelectedRowCount();
            if(filasSeleccionadas == 1){
                row_selected = jTable1.getSelectedRow();
                System.out.println("Fila seleccionada: " + row_selected);
                System.out.println("Pasajero ID: " + pasajerosDTO.get(row_selected).getId());
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        //Si se selecciono una persona se pasa a la interfaz modificar usuario
        Object[] options = { "No", "Si"};
            int opcion = JOptionPane.showOptionDialog(null, "¿Desea dar de alta un pasajero?", "Dar de Alta Pasajero",
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcion == 1) {
                System.out.println("Pasar a la interface alta de pasajero");
                frame.cambiarPanel(VentanaPrincipal.PANE_DAR_ALTA_PASAJERO);
            } else System.out.println("Seguir buscando");

    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jComboBoxTipoDocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoDocItemStateChanged
        // TODO add your handling code here:
        //Sino se selecciona tipo de documento no se puede poner numero
        if(jComboBoxTipoDoc.getSelectedItem()!=null){
            JTextDocumento.setEnabled(true);
        }else{
            JTextDocumento.setEnabled(false);
            JTextDocumento.setText(null);
        }

    }//GEN-LAST:event_jComboBoxTipoDocItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame.cambiarPanel(VentanaPrincipal.PANE_MENU_PRINCIPAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        pagActual--;
        lPag.setText("Página "+pagActual+"/"+pagsTotales);

        if (pisoInclusivo + MAX_FILAS >= pasajerosDTO.size())
                techoExclusivo -= pasajerosDTO.size() - pisoInclusivo;
        else
                techoExclusivo -= MAX_FILAS;
        pisoInclusivo -= MAX_FILAS;

        bAdelante.setEnabled(true);
        if (pisoInclusivo == 0) bAtras.setEnabled(false);
        
        cargarPagina();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdelanteActionPerformed
        // TODO add your handling code here:
        pagActual++;
        lPag.setText("Página "+pagActual+"/"+pagsTotales);

        pisoInclusivo += MAX_FILAS;
        bAtras.setEnabled(true);
        if (pisoInclusivo + MAX_FILAS >= pasajerosDTO.size())
        {
                techoExclusivo += pasajerosDTO.size() - pisoInclusivo;
                bAdelante.setEnabled(false);
        }
        else
                techoExclusivo += MAX_FILAS;
        
        cargarPagina();
    }//GEN-LAST:event_bAdelanteActionPerformed

    private void JTextNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextNombreKeyReleased
        // TODO add your handling code here:
        //Para que el ingreso de los datos sea siempre en mayuscula
//        int position = JTextNombre.getCaretPosition();
//        JTextNombre.setText(JTextNombre.getText().toUpperCase());
//        JTextNombre.setCaretPosition(position);
    }//GEN-LAST:event_JTextNombreKeyReleased

    private void JTextApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextApellidoKeyReleased
        // TODO add your handling code here:
//        int position = JTextApellido.getCaretPosition();
//        JTextApellido.setText(JTextApellido.getText().toUpperCase());
//        JTextApellido.setCaretPosition(position);
    }//GEN-LAST:event_JTextApellidoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextApellido;
    private javax.swing.JTextField JTextDocumento;
    private javax.swing.JTextField JTextNombre;
    private javax.swing.JButton bAdelante;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox<TipoDocumento> jComboBoxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lPag;
    // End of variables declaration//GEN-END:variables
}
