/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dto.PersonaFisicaDTO;
import entidades.TipoDocumento;
import gestores.GestorDePersonas;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Nahuel Riquelme
 */
public class PanelOcuparHabitacion extends javax.swing.JPanel {
    private final VentanaPrincipal frame;
    private final GestorDePersonas gestorPersonas = GestorDePersonas.getInstance();
    private PasajerosTableModel model;
    private PasajerosTableModel2 model2;
    private int row_selected;
    private int row_selected2;
    private List<PersonaFisicaDTO> pasajerosDTO;
    private List<PersonaFisicaDTO> paginado;
    public static int MAX_FILAS = 10;
    private int pisoInclusivo = 0;
    private int techoExclusivo =  MAX_FILAS;
    private int pagActual;
    private int pagsTotales;
    private boolean pasajeroCargado;
    private PersonaFisicaDTO personaSeleccionada1;
    private PersonaFisicaDTO personaSeleccionada2;

    /**
     * Creates new form OcuparHabitacion
     * @param frame
     */
    public PanelOcuparHabitacion(VentanaPrincipal frame) {
        initComponents();
        this.frame = frame;
        cargarModelo();
    }
    
    private void cargarModelo(){
        model = new PasajerosTableModel();
        model2 = new PasajerosTableModel2();
        jTable1.setModel(model);
        jTable2.setModel(model2);
        pasajeroCargado = false;
    
        //Le agrego el radiobutton a las tablas
        agregarRadioButton();        
    }
    
    private void agregarRadioButton(){
        class MyTableCellRenderer extends JRadioButton implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
           this.setSelected(isSelected);
            setBackground(Color.WHITE);
           return this;
        }
    }
        TableColumnModel cm = jTable1.getColumnModel();
        cm.addColumn(new TableColumn(0, 10, new MyTableCellRenderer(), null));
        cm.moveColumn(cm.getColumnCount() - 1, 0);
        
        TableColumnModel cm2 = jTable2.getColumnModel();
        cm2.addColumn(new TableColumn(0, 10, new MyTableCellRenderer(), null));
        cm2.moveColumn(cm2.getColumnCount() - 1, 0);
    }
    
    private void cargarDatosBusqueda(){
        String nombre = JTextNombre.getText();
        String apellido = JTextApellido.getText();
        String tipoDocumento;
        if(jComboBoxTipoDoc.getSelectedItem() == null){
            tipoDocumento = "";
        }else tipoDocumento = jComboBoxTipoDoc.getSelectedItem().toString();
        String nroDocumento = JTextDocumento.getText();
        pasajerosDTO = gestorPersonas.buscarPasajero(nombre,apellido,tipoDocumento,nroDocumento);
        paginarDatos();
    }
    
    private void paginarDatos(){
        //Modifico el jLabel con la cantidad de paginas
        pagActual = pisoInclusivo / MAX_FILAS + 1;
        pagsTotales = pasajerosDTO.size() / MAX_FILAS + ((pasajerosDTO.size() % MAX_FILAS == 0)? 0 : 1);
        lPag.setText("Pagina "+pagActual+"/"+pagsTotales);
        
        //Carga la pagina actual
        cargarPagina();
        
        if (pasajerosDTO.size() / MAX_FILAS > 0)
            bAdelante.setEnabled(true);
        else
            bAdelante.setEnabled(false);
    }
    
    private void cargarPagina(){
        paginado = pasajerosDTO.stream().skip((pagActual-1)*MAX_FILAS).limit(MAX_FILAS).collect(Collectors.toList());
        model.setDatos(paginado);
        model.fireTableDataChanged(); 
    }
    
    private void filtrarPersonaCargada(){
        paginado = pasajerosDTO.stream().filter(p -> model2.getDatos().contains(p))
                .skip((pagActual-1)*MAX_FILAS).limit(MAX_FILAS).collect(Collectors.toList());
        model.setDatos(paginado);
        model.fireTableDataChanged();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTextNombre = new javax.swing.JTextField();
        jComboBoxTipoDoc = new javax.swing.JComboBox<>();
        DefaultComboBoxModel tipoDocModel = new DefaultComboBoxModel();
        tipoDocModel.addElement(null);
        for(TipoDocumento t: TipoDocumento.values()){
            tipoDocModel.addElement(t);
        }
        jComboBoxTipoDoc.setModel(tipoDocModel);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTextApellido = new javax.swing.JTextField();
        JTextDocumento = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.getTableHeader().setReorderingAllowed(false);
        jButtonCargarAcompañante = new javax.swing.JButton();
        jButtonCargarPasajero = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        lPag = new javax.swing.JLabel();
        bAdelante = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel5 = new javax.swing.JPanel();
        jButtonQuitar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTable2.getTableHeader().setReorderingAllowed(false);
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1184, 798));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Criterios de busqueda");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setText("Nombres(s)");

        jLabel2.setText("Tipo de documento");

        JTextNombre.setNextFocusableComponent(JTextApellido);
        JTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTextNombreKeyReleased(evt);
            }
        });

        jComboBoxTipoDoc.setNextFocusableComponent(JTextDocumento);
        jComboBoxTipoDoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoDocItemStateChanged(evt);
            }
        });

        jLabel4.setText("Apellido(s)");

        jLabel5.setText("Numero de documento");

        JTextApellido.setNextFocusableComponent(jComboBoxTipoDoc);
        JTextApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTextApellidoKeyReleased(evt);
            }
        });

        JTextDocumento.setEnabled(false);
        JTextDocumento.setNextFocusableComponent(jButtonBuscar);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextDocumento)
                    .addComponent(JTextApellido))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JTextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Resultados de busqueda");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonCargarAcompañante.setText("Cargar acompañante");
        jButtonCargarAcompañante.setEnabled(false);
        jButtonCargarAcompañante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarAcompañanteActionPerformed(evt);
            }
        });

        jButtonCargarPasajero.setText("Cargar pasajero");
        jButtonCargarPasajero.setEnabled(false);
        jButtonCargarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarPasajeroActionPerformed(evt);
            }
        });

        bAtras.setText("<");
        bAtras.setDoubleBuffered(true);
        bAtras.setEnabled(false);
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        lPag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lPag.setText("Pagina 0/0");

        bAdelante.setText(">");
        bAdelante.setEnabled(false);
        bAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonCargarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAdelante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCargarAcompañante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCargarAcompañante)
                            .addComponent(jButtonCargarPasajero)
                            .addComponent(lPag)
                            .addComponent(bAdelante)
                            .addComponent(bAtras)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButtonQuitar.setText("Quitar");
        jButtonQuitar.setEnabled(false);
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filler4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonQuitar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Personas cargadas");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Aceptar");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Seguir cargando");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Cargar otra habitacion");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Salir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jButton1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTextNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextNombreKeyReleased
        // TODO add your handling code here:
        //Para que el ingreso de los datos sea siempre en mayuscula
        //        int position = JTextNombre.getCaretPosition();
        //        JTextNombre.setText(JTextNombre.getText().toUpperCase());
        //        JTextNombre.setCaretPosition(position);
    }//GEN-LAST:event_JTextNombreKeyReleased

    private void jComboBoxTipoDocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoDocItemStateChanged
        // TODO add your handling code here:
        //Sino se selecciona tipo de documento no se puede poner numero
        if(jComboBoxTipoDoc.getSelectedItem()!=null){
            JTextDocumento.setEnabled(true);
        }else{
            JTextDocumento.setEnabled(false);
            JTextDocumento.setText(null);
        }
    }//GEN-LAST:event_jComboBoxTipoDocItemStateChanged

    private void JTextApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextApellidoKeyReleased
        // TODO add your handling code here:
        //        int position = JTextApellido.getCaretPosition();
        //        JTextApellido.setText(JTextApellido.getText().toUpperCase());
        //        JTextApellido.setCaretPosition(position);
    }//GEN-LAST:event_JTextApellidoKeyReleased

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        //Carga los datos en la tabla
        cargarDatosBusqueda();        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        pagActual--;
        lPag.setText("Pagina "+pagActual+"/"+pagsTotales);

        if (pisoInclusivo + MAX_FILAS >= pasajerosDTO.size())
        techoExclusivo -= pasajerosDTO.size() - pisoInclusivo;
        else techoExclusivo -= MAX_FILAS; 
        
        pisoInclusivo -= MAX_FILAS;

        bAdelante.setEnabled(true);
        if (pisoInclusivo == 0) bAtras.setEnabled(false);

        cargarPagina();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdelanteActionPerformed
        // TODO add your handling code here:
        pagActual++;
        lPag.setText("Pagina "+pagActual+"/"+pagsTotales);

        pisoInclusivo += MAX_FILAS;
        bAtras.setEnabled(true);
        if (pisoInclusivo + MAX_FILAS >= pasajerosDTO.size())
        {
            techoExclusivo += pasajerosDTO.size() - pisoInclusivo;
            bAdelante.setEnabled(false);
        }
        else techoExclusivo += MAX_FILAS;

        cargarPagina();
    }//GEN-LAST:event_bAdelanteActionPerformed

    private void jButtonCargarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarPasajeroActionPerformed
        // TODO add your handling code here:
        pasajerosDTO.get(row_selected).setCategoria("Pasajero");
        //Agrego la persona a la tabla2 de personas cargadas
        model2.agregarPersona(model.getDatos().get(row_selected));
        model2.fireTableDataChanged();
        pasajeroCargado = true;
        //Elimino la persona de la tabla1 resultados de busqueda
        pasajerosDTO.remove(personaSeleccionada1);
        cargarPagina();
        //Limpio la seleccion y desactivo botones
        jTable1.clearSelection();
        jButtonCargarAcompañante.setEnabled(false);
        jButtonCargarPasajero.setEnabled(false);
    }//GEN-LAST:event_jButtonCargarPasajeroActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            int filasSeleccionadas = jTable1.getSelectedRowCount();
            if(filasSeleccionadas == 1){
                row_selected = jTable1.getSelectedRow();
                System.out.println(model.getDatos().get(row_selected).getApellido());
                personaSeleccionada1 = model.getDatos().get(row_selected);
                if(!pasajeroCargado)jButtonCargarPasajero.setEnabled(true);
                jButtonCargarAcompañante.setEnabled(true);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonCargarAcompañanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarAcompañanteActionPerformed
        // TODO add your handling code here:
        pasajerosDTO.get(row_selected).setCategoria("Acompañante");
        //Agrego la persona a la tabla2 de personas cargadas
        model2.agregarPersona(model.getDatos().get(row_selected));
        model2.fireTableDataChanged();
        //Elimino la persona de la tabla1 resultados de busqueda
        pasajerosDTO.remove(personaSeleccionada1);
        cargarPagina();
        //Limpio la seleccion y desactivo los botones 
        jTable1.clearSelection();
        jButtonCargarAcompañante.setEnabled(false);
        jButtonCargarPasajero.setEnabled(false);
    }//GEN-LAST:event_jButtonCargarAcompañanteActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int filasSeleccionadas = jTable2.getSelectedRowCount();
        if(filasSeleccionadas == 1){
            row_selected2 = jTable2.getSelectedRow();
            System.out.println(model2.getDatos().get(row_selected2).getApellido());
            personaSeleccionada2 = model2.getDatos().get(row_selected2);
            jButtonQuitar.setEnabled(true);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        // TODO add your handling code here:
        //Si elimino el pasajero, habilito para que se cargue otro
        if(model2.getDatos().get(row_selected2).getCategoria().equals("Pasajero"))pasajeroCargado=false;
        //Agrego la persona a la tabla1 de resultados de busqueda
        pasajerosDTO.add(personaSeleccionada2);
        pasajerosDTO.sort((p1,p2) -> p1.compareTo(p2));
        cargarPagina();
        //Elimino la persona de la tabla2 de personas cargadas
        model2.quitarPersona(row_selected2);
        model2.fireTableDataChanged();
        //Limpio la seleccion y desactivo el boton
        jTable2.clearSelection();
        jButtonQuitar.setEnabled(false);
    }//GEN-LAST:event_jButtonQuitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextApellido;
    private javax.swing.JTextField JTextDocumento;
    private javax.swing.JTextField JTextNombre;
    private javax.swing.JButton bAdelante;
    private javax.swing.JButton bAtras;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCargarAcompañante;
    private javax.swing.JButton jButtonCargarPasajero;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JComboBox<TipoDocumento> jComboBoxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lPag;
    // End of variables declaration//GEN-END:variables
}
