/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import dto.ServicioPrestadoDTO;
import entidades.Estadia;
import entidades.PersonaFisica;
import entidades.PersonaJuridica;
import gestores.GestorDePersonas;
import java.math.BigInteger;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Fede
 */
public class PanelFacturarTercero extends javax.swing.JPanel {
    private final VentanaPrincipal frame;
    private final GestorDePersonas gestorPersonas = GestorDePersonas.getInstance();

    
    private final Estadia estadia;
    private final LocalTime hora;
    private final List<PersonaFisica> pasajeros;
    private List<ServicioPrestadoDTO> servPendientes;
    
    private BigInteger cuit;
    private PersonaJuridica responsable;

    /**
     * Creates new form PanelFacturarTercero
     * @param frame
     * @param e
     * @param h
     * @param lP
     */
    
    //Viene de menú principal
    public PanelFacturarTercero(VentanaPrincipal frame, Estadia e, LocalTime h, List<PersonaFisica> lP) {
        initComponents();
        this.frame = frame;
        this.estadia = e;
        this.hora = h;
        this.pasajeros = lP;
        this.servPendientes = null;
        
        limitarCampos();
    }
    
    //Viene de facturar
    public PanelFacturarTercero(VentanaPrincipal frame, Estadia e, LocalTime h, List<PersonaFisica> lP, List<ServicioPrestadoDTO> sP) {
        initComponents();
        this.frame = frame;
        this.estadia = e;
        this.hora = h;
        this.pasajeros = lP;
        this.servPendientes = sP;
        
        limitarCampos();
    }
    
    private void limitarCampos(){
        //Limita la longitud de los campos
        jTextCUIT.setDocument(new JTextFieldLimit(12));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextCUIT = new javax.swing.JTextField();
        jTextRazon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datos de Facturación a Tercero");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextCUIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCUITKeyTyped(evt);
            }
        });

        jTextRazon.setEnabled(false);

        jLabel2.setText("Razón Social");

        jLabel3.setText("CUIT (*)");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextCUIT, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        //Mensaje no escribiste cuit
        if (cuit==null){
            Object[] options = { "No", "Si"};
            int opcion = JOptionPane.showOptionDialog(null, "¿Desea dar de alta un responsable de pago?", "Responsable no encontrado",
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcion == 1) {
                System.out.println("Pasar a la interface alta de responsable de pago");
                frame.cambiarPanel(0);
                
            } else System.out.println("Seguir buscando");
        }else{
            
            //Si la lista de servicios pendientes es null venimos del menu principal
            if(servPendientes == null){
                frame.setContentPane(new PanelFacturar(frame,responsable, estadia, hora, pasajeros));
                frame.setTitle("Facturar");
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.getContentPane().setVisible(false);
                frame.getContentPane().setVisible(true);
                
            }else{
                
                //System.out.println(estadia.getHabitacion().getEstado().name() + "\n");
                frame.setContentPane(new PanelFacturar(frame,responsable, estadia, hora, pasajeros, servPendientes));
                frame.setTitle("Facturar");
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.getContentPane().setVisible(false);
                frame.getContentPane().setVisible(true);
            }
            
        }
        
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        //Mensaje Desea Cerrar???
        Object[] options = { "No", "Si"};
            int opcion = JOptionPane.showOptionDialog(null, "¿Desea volver al menú principal, todos los cambios se desecharán?", "Cancelar",
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcion == 1) {
                System.out.println("Volver al menú principal");
                frame.cambiarPanel(0);
            }   
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextCUITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCUITKeyTyped
        // TODO add your handling code here:
        //Cuando llegue a 11 largamos a buscar
        if(jTextCUIT.getText().length()==11){
            //Controlar que esté bien escrito
            try{
                //Buscar la razón social            
                cuit = new BigInteger(jTextCUIT.getText());
            }catch (Exception ex){
                Object opciones[] = {"Aceptar"};
                JOptionPane.showOptionDialog(
                    null, 
                    "El cuit debe ser un campo NUMÉRICO de 11 caracteres", 
                    "Error", 
                    JOptionPane.DEFAULT_OPTION, 
                    JOptionPane.INFORMATION_MESSAGE, 
                    null, 
                    opciones,
                    opciones[0]
                );
            }
            
            try{
                responsable = gestorPersonas.findPersonaJuridica(cuit);
                jTextRazon.setText(responsable.getRazonSocial());
            } catch (Exception ex){
                Object opciones[] = {"Aceptar"};
                JOptionPane.showOptionDialog(
                    null, 
                    "Responsable de pago con cuit: " + cuit + " no encontrado", 
                    "Error", 
                    JOptionPane.DEFAULT_OPTION, 
                    JOptionPane.INFORMATION_MESSAGE, 
                    null, 
                    opciones,
                    opciones[0]
                );
            }
        }
    }//GEN-LAST:event_jTextCUITKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCUIT;
    private javax.swing.JTextField jTextRazon;
    // End of variables declaration//GEN-END:variables

    /*
    private void obtenerDatos() {
        //cuit = BigInteger.valueOf(jTextCUIT.getText());
        cuit = new BigInteger(jTextCUIT.getText());
        responsable = gestorPersonas.findPersonaJuridica(cuit);
        jTextRazon.setText(responsable.getRazonSocial());
    }
    */
    
    /*
    public PanelFacturarTercero(VentanaPrincipal frame, Estadia e) {
        initComponents();
        this.frame = frame;
        this.estadia = e;
        //obtenerDatos(); //Se abre cuando el cuit tiene 11 caraceteres escritos
    }
    */
    
}
